# Configuration for Windows, Mingw compiler
WHERE=C:/ocamlmgw/lib/ocaml
include C:/ocamlmgw/lib/ocaml/Makefile.config
TK_ROOT=c:/tcl
TK_DEFS=-I$(TK_ROOT)/include
TK_LINK=$(TK_ROOT)/bin/tk85.dll $(TK_ROOT)/bin/tcl85.dll -lws2_32
